name: Docs - Automated Publishing

on:
  push:
    branches: [ main, master ]
    paths:
      - 'README.md'
      - '*.md'
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build documentation
      run: |
        echo "📚 Building docs..."
        mkdir -p docs-site
        
        # Create simple docs page
        cat > docs-site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Heavens Above - Documentation</title>
            <style>
                body { font-family: -apple-system, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; line-height: 1.6; }
                h1 { color: #2c3e50; }
                code { background: #f4f4f4; padding: 3px 6px; border-radius: 3px; }
                pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
            </style>
        </head>
        <body>
            <h1>📡 Heavens Above Documentation</h1>
            <p>Scripts for scraping the Heavens Above website.</p>
            <h2>Installation</h2>
            <pre>npm install</pre>
            <h2>Usage</h2>
            <pre>node run.js</pre>
            <p><small>Last updated: $(date)</small></p>
        </body>
        </html>
        EOF
        
        # Copy README
        cp README.md docs-site/ 2>/dev/null || echo "No README found"
        
        echo "✅ Docs built!"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-site
        publish_branch: gh-pages-docs
